spring:
  jpa:
    database: mysql
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3307/inventory
    username: mysqluser
    password: mysqlpw
  sql:
    init:
      platform: org.hibernate.dialect.MySQL5Dialect